name: 'Example command action'
description: 'Example greet action'
inputs:
  inputString:
    description: 'Some input string'
    required: false
    default: 'Default string'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: 'composite'
  steps:
    - run: echo ${{ inputs.inputString }}
      shell: bash
    - run: ${{ github.action_path }}/script.sh
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
