name: Test composite action

on:
  push:
  pull_request:

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    name: Example run
    steps:
      - uses: pavolloffay/github-actions/helloworld-composite/@main
        id: foo
        with:
          inputString: John Doe
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: ls file.json

