name: Test docker action

on:
  push:
  pull_request:

jobs:
  test-docker-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        # The container is always build per action run even when tagged version is used
        uses: pavolloffay/github-actions/helloworld-docker@v1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: List files
        run: ls -al
